# Generated by Django 5.2.17 on 2026-09-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text='مثلاً: 💧', max_length=50)),
                ('color', models.CharField(blank=True, default='#0d6efd', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'روزانه'), ('every_n_days', 'هر N روز'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('custom', 'سفارشی')], default='every_n_days', max_length=20)),
                ('interval_days', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='plants.plant')),
                ('care_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='care.caretype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField()),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('product', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='care_logs/')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(default='web', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to='plants.plant')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='care.careschedule')),
                ('care_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='care.caretype')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
