# Generated by Django 5.2.17 on 2026-09-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('active', 'فعال'), ('rejected', 'رد شده'), ('suspended', 'معلق')], default='active', max_length=20),
        ),
    ]
