# Generated by Django 5.2.17 on 2026-09-25 14:29

import django.db.models.deletion
import qrcodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_type', models.CharField(choices=[('plant', 'Plant QR'), ('action', 'Action QR')], max_length=20)),
                ('action_type', models.CharField(blank=True, help_text='برای Action QR: مثلاً watering', max_length=50)),
                ('token', models.CharField(db_index=True, default=qrcodes.models.generate_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('revoked', 'غیرفعال'), ('expired', 'منقضی')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='plants.plant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='qrcodes.qrcode')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
