# Generated by Django 5.2.17 on 2026-09-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, help_text='تصویر PNG تولید شده از QR', null=True, upload_to='qrcodes/'),
        ),
    ]
