# Generated by Django 5.2.17 on 2026-09-25 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['owner', 'is_active'], name='plants_plan_owner_i_ccf8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['status'], name='plants_plan_status_a920d9_idx'),
        ),
    ]
